app/__init__.py
from flask import Flask
from config import Config
from .site.routes import site
from .api.routes import api
from .authentication.routes import auth

# from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from models import db as root_db, login_manager, ma
from flask_cors import CORS
from helpers import JSONEncoder

app = Flask(__name__)
CORS(app)

app.register_blueprint(site)
app.register_blueprint(auth)
app.register_blueprint(api)

app.json_encoder = JSONEncoder
app.config.from_object(Config)
root_db.init_app(app)
login_manager.init_app(app)
ma.init_app(app)
migrate = Migrate(app, root_db)

app/api/routes.py
from flask import Blueprint, request, jsonify, render_template
from helpers import token_required
from models import db, User, Book, book_schema, books_schema

api = Blueprint('api',__name__, url_prefix='/api')

@api.route('/getdata')
@token_required
def getdata(current_user_token):
    return {
        'title': 'Pride and Prejudice',
        'author_name': 'Jane Austen',
        'isbn_number': '9780140430721',
        'genre': 'Romance'
        }

@api.route('/book', methods = ['POST'])
@token_required
def create_book(current_user_token):
    title = request.json['title']
    author_name = request.json['author_name']
    isbn_number = request.json['isbn_number']
    genre = request.json['genre']
    user_token = current_user_token.token

    print(f'Book Added: {current_user_token.token}')

    book = Book(title, author_name, isbn_number, genre, user_token = user_token )

    db.session.add(book)
    db.session.commit()

    response = book_schema.dump(book)
    return jsonify(response)

@api.route('/book', methods = ['GET'])
@token_required
def get_book(current_user_token):
    a_book = current_user_token.token
    books = Book.query.filter_by(user_token = a_book).all()
    response = books_schema.dump(books)
    return jsonify(response)

@api.route('/book/<id>', methods = ['GET'])
@token_required
def get_book_two(current_user_token, id):
    fan = current_user_token.token
    if fan == current_user_token.token:
        search = Book.query.get(id)
        response = book_schema.dump(search)
        return jsonify(response)
    else:
        return jsonify({"message": "Valid Token Required"}),401


@api.route('/book/<id>', methods = ['POST','PUT'])
@token_required
def update_book(current_user_token,id):
    search = Book.query.get(id) 
    search.title = request.json['title']
    search.author_name = request.json['author_name']
    search.isbn_number = request.json['isbn_number']
    search.genre = request.json['genre']
    search.user_token = current_user_token.token

    db.session.commit()
    response = book_schema.dump(search)
    return jsonify(response)

@api.route('/book/<id>', methods = ['DELETE'])
@token_required
def delete_book(current_user_token, id):
    book = Book.query.get(id)
    book.user_token = current_user_token.token
    db.session.delete(book)
    db.session.commit()
    response = book_schema.dump(book)
    return jsonify(response)

app/authentication/routes.py
from forms import UserLoginForm
from models import User, db
from werkzeug.security import check_password_hash
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_user, logout_user, current_user, login_required, LoginManager

auth = Blueprint('auth', __name__, template_folder='auth_templates')

@auth.route('/sign_up', methods = ['GET', 'POST'])
def sign_up():
    form = UserLoginForm()


    if request.method == 'POST' and form.validate_on_submit():
        email = form.email.data
        password = form.password.data
        print(email, password)

        user = User(email, password = password)

        db.session.add(user)
        db.session.commit()

        flash(f'You have successfully created a user account {email}', 'User-created')
        return redirect(url_for('site.home'))
    # raise Exception('Invalid form data: Please check your form')
    return render_template('sign_up.html', form = form)

@auth.route('/sign_in', methods = ['Get', 'Post'])
def sign_in():
    form = UserLoginForm()

    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            print(email, password)

            logged_user = User.query.filter(User.email == email).first()
            if logged_user and check_password_hash(logged_user.password, password):
                login_user(logged_user)
                flash('You have successfully logged into your account!', 'auth-success')
                return redirect(url_for('site.profile'))
            else:
                flash('Unfortunately, the details you have entered are incorrect. Please try again.', 'auth-failed')
                return redirect(url_for('auth.sign_in'))
    except:
        raise Exception('Invalid form data. Please try again.')
    return render_template('sign_in.html', form=form)

app/site/routes.py
from flask import Blueprint, render_template

site = Blueprint('site', __name__, template_folder='site_templates')

@site.route('/')
def home():
    return render_template('index.html')

@site.route('/profile')
def profile():
    return render_template('profile.html')

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="../static/css/main.css">
<title>Kuda's Library</title>
<style>
body{
    background-color: cornsilk;
}
nav{
    background-color: cornsilk;
}
.list-unstyled{
    text-decoration: none;
    color: inherit;
}
</style>
</head>
<body>
<nav class="navbar navbar-expand text-dark navbar-fixed-top" style="text-decoration: none;">
    <a class="navbar-brand" href="">Kuda's Library</a>
    <ul class="list-unstyled navbar-nav mr-auto mt-6 mt-lg-6">
        <li class="nav-item active d-flex justify-content-end">
            <a class="nav-link" href="{{ url_for('site.home') }}">Home<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item d-flex justify-content-end">
            <a class="nav-link" href="{{ url_for('site.profile') }}">Profile</a>
        </li>
        {% if current_user.is_authenticated %}
        <li class="nav-item d-flex justify-content-end">
            <a class="nav-link" href="{{ url_for('auth.sign_up') }}"></a>
        </li>
        {% else %}
        <li class="nav-item d-flex justify-content-end">
            <a class="nav-link" href="{{ url_for('auth.sign_in') }}">Sign In</a>
        </li>
        <li class="nav-item d-flex justify-content-end">
            <a class="nav-link" href="{{ url_for('auth.sign_up') }}">Sign Up</a>
        </li>
        {% endif %}
    </ul>
</nav>


{% block content %}
{% endblock %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>

app/templates/forms.html
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class = "form-control", placeholder = "place email here...") }}
        </fieldset>
    </div>
        
        <fieldset id="pass-field">
            {{ form.password.label }}
            {{ form.password(class = "form-control", placeholder = "Place password here ") }}
        </fieldset>

          <!-- Submit button area -->
        {{ form.submit_button(class = "btn btn-primary btn-block mt-2")}}
</form>

app/templates/search.html
<!-- Add later to search for book -->
<style>
* {
    box-sizing: border-box;
    display: flex;
    justify-content: center;
    align-items: center;
    color:plum;
}
.card-img{
    filter: blur(5px);
    -webkit-filter: blur(5px);
    width: 100%;
    height: 75%;
    z-index: -1;
}
</style>    
<section style="color: plum;"class="align-items-center d-flex justify-content-center">
    <title>Search For A Book</title>
    <div class="card">
        <div class="card-image"></div>
        <img style="z-index: -1;"src="/app/static/images/pexels-pixabay-207732.jpg" alt="Books in grayscale"><a href="https://pixabay.com/?ref=pexels">Taken by Pixaby on pexels</a>
        <div class="card-img-overlay col-lg-6">
            <form action="bg-form card-img-overlay">
                <h1 class="fw-bold text-light display-2">Book Search</h1>
                <p class="fs-6 text-light">Please Type The Details of The Book You Are Looking For.</p>
                <!--search -->
                <div class="form-floating">
                    <label for="book-search" class="text-secondary">Title</label>
                    <input class="form-control" type="text" id="title" placeholder="Book Title">
                </div>
                <!-- Author_name -->
                <div class="form-floating">
                    <label for="password" class="text-secondary">Author Name</label>
                    <input class="form-control" type="text" id="author" placeholder="Author Name">
                </div>
                <!-- isbn_number -->
                <div class="custom-control custom-checkbox custom-control-inline">
                    <label class="text-light" for="isbn_number">If you know the ISBN Number, Enter it Here: </label>
                    <input type="text" class="custom-control-label" placeholder="ISBN Number">
                </div>
                <!-- Category -->
                <form class="form-inline">
                    <label class="my-1 mr-2" for="inlineFormCustomSelectPref">Pick A Category</label>
                    <select class="custom-select my-1 mr-sm-2" id="inlineFormCustomSelectPref">
                      <option selected>Choose...</option>
                      <option value="1">Educational</option>
                      <option value="2">Thriller</option>
                      <option value="3">Fantasy</option>
                      <option value="4">Romance</option>
                      <option value="5">Cooking</option>
                      <option value="6">Religous</option>
                      <option value="7">Children's</option>
                    </select><br>
                    <button type="submit" class="btn btn-primary my-1">Submit</button>
                  </form>
            </form>
        </div>
    </div>
</section>

app/templates/table.html
<div class="container">
    <!-- <section class="bg-secondary text-dark text-center shadow">
        <div class="container bg-secondary">
            <div class="row">
                <div class="d-flex bg-light align-items-center justify-content-evenly">
                    <h1 class="col text-center">Your Library Inventory</h1>
                </div>
            </div>
        </div>
    </section> -->
    <!-- Add the inventory of the account here? -->
    <table class="table caption-top">
        <caption>List of books you have</caption>
        <thead>
            <tr>
                <th scope="col">Title</th>
                <th scope="col">Author Name</th>
                <th scope="col">ISBN Number</th>
                <th scope="col">Category</th>
            </tr>
        </thead>
        <tbody>
            <!-- Add the information into the table-->
        </tbody>    
    </table>
    <section class="bg-dark text-center">
        <div class="container">
            <div class="row">
                <div class="images">
                    <img class="image" style="width:50%; height:50%;" src="/app/static/images/pexels-rafael-cosquiere-2041540.jpg" alt="Second slide"><br><a href="https://www.pexels.com/photo/white-wooden-bookshelves-1319855/">Photo by Rafael Cosquiere from Pexels</a> 
                    </div>
            </div>
        </div>
    </section>
</div>